// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductReviews.Context;

namespace ProductReviews.Migrations
{
    [DbContext(typeof(Context.DbContext))]
    [Migration("20211122165925_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProductReviews")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductReviews.DomainModels.ProductReviewModel", b =>
                {
                    b.Property<int>("ProductReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductReviewContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductReviewHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProductReviewIsHidden")
                        .HasColumnType("bit");

                    b.HasKey("ProductReviewID");

                    b.ToTable("_productReviews");

                    b.HasData(
                        new
                        {
                            ProductReviewID = 1,
                            ProductID = 1,
                            ProductReviewContent = "Lovely Shoes.",
                            ProductReviewDate = new DateTime(2021, 11, 22, 16, 59, 24, 617, DateTimeKind.Local).AddTicks(1879),
                            ProductReviewHeader = "Wow!",
                            ProductReviewIsHidden = false
                        },
                        new
                        {
                            ProductReviewID = 2,
                            ProductID = 1,
                            ProductReviewContent = "Best shirt since sliced bread.",
                            ProductReviewDate = new DateTime(2021, 11, 22, 16, 59, 24, 622, DateTimeKind.Local).AddTicks(1629),
                            ProductReviewHeader = "Amazing!",
                            ProductReviewIsHidden = false
                        },
                        new
                        {
                            ProductReviewID = 3,
                            ProductID = 2,
                            ProductReviewContent = "Did not receive order...",
                            ProductReviewDate = new DateTime(2021, 11, 22, 16, 59, 24, 622, DateTimeKind.Local).AddTicks(1680),
                            ProductReviewHeader = "Terrible!",
                            ProductReviewIsHidden = false
                        },
                        new
                        {
                            ProductReviewID = 4,
                            ProductID = 2,
                            ProductReviewContent = "Great Service.",
                            ProductReviewDate = new DateTime(2021, 11, 22, 16, 59, 24, 622, DateTimeKind.Local).AddTicks(1686),
                            ProductReviewHeader = "Lovely Jubbly!",
                            ProductReviewIsHidden = false
                        },
                        new
                        {
                            ProductReviewID = 5,
                            ProductID = 3,
                            ProductReviewContent = "I wanted a schmedium but I received a Large. I'm so mad.",
                            ProductReviewDate = new DateTime(2021, 11, 22, 16, 59, 24, 622, DateTimeKind.Local).AddTicks(1690),
                            ProductReviewHeader = "WrongSize!!!!",
                            ProductReviewIsHidden = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
